### PR TITLE
Portfolio Mobile menu

### PR DESCRIPTION
**Pull request by maccony202**
Implementation of eslint & humburger menu & page transition.

### CODE REVIEW

**Review by Santiago220991 — CHANGES_REQUESTED** [review]
Hi @maccony202, 
I'm Santiago your reviewer for this PR. :wave: :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
:heavy_check_mark: Followed GitHub flow.
:heavy_check_mark: Good commit messages.

## Required Changes ♻️
- As this is a javascript project, kindly make sure that you are also using JavaScript linters (Eslint). You can get more information about[ this here](https://github.com/microverseinc/linters-config).

- Kindly make sure to update the README file. Last week Microverse provided a [new template](https://github.com/microverseinc/readme-template) that must be used on every project. :briefcase: :briefcase: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by maccony202** [comment]
> Hi @maccony202, I'm Santiago your reviewer for this PR. 👋 👋
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
>  [ 68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966 ](https://camo.githubusercontent.com/11a2828e8eaeee4ff859c35836211f3e1ec76e0feab518dac8a20820f1591122/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966) [ ](https://camo.githubusercontent.com/11a2828e8eaeee4ff859c35836211f3e1ec76e0feab518dac8a20820f1591122/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## Highlights
> ✔️ Followed GitHub flow. ✔️ Good commit messages.
> 
> ## Required Changes ♻️
> * As this is a javascript project, kindly make sure that you are also using JavaScript linters (Eslint). You can get more information about[ this here](https://github.com/microverseinc/linters-config).
> * Kindly make sure to update the README file. Last week Microverse provided a [new template](https://github.com/microverseinc/readme-template) that must be used on every project. 💼 💼
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Please there is javascript linters in the project so kindly check it well

**Comment by medaminedev66** [comment]
Hello @maccony202 👋,

_This is an additional review as a result of the second opinion request._

As far as I can see, you still did not set up linters for JavaScript. You are supposed to use [HTML/CSS+JavaScript](https://github.com/microverseinc/linters-config/tree/master/html-css-js) configuration. After adding the new `linters.yml`, kindly ensure that "Linters / Eslint" is added next to "Linters / Lighthouse", "Linters / Webhint", "Linters / Stylelint" ... as shown below:

image

Kindly remember to use the [second version](https://github.com/microverseinc/readme-template) of the readme template as requested by the previous reviewer.

Keep rocking 🚀!

**Review by muneebulrehman — APPROVED** [review]
Hi @maccony202 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- No linter errors
- Good follow-up with the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
